[package]
name = "mood"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.1", features = [ "derive" ] }
env_logger = "0.11.8"
image = "0.25.6"
log = "0.4.27"
nalgebra = "0.33.2"
pollster = "0.4.0"
wgpu = "25.0.2"
winit = "0.30.11"
