[workspace]
resolver = "3"
members = ["client", "server"]
default-members = ["client"]

[workspace.package]
version = "0.1.0"
authors = ["Neil Hommes <nhommes@neilhommes.xyz>"]
description = "A multiplayer FPS game"

